pythondockername: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/images/pythondocker
        build-args: |
          N_VERSION=${{steps.vars.outputs.tag}}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/pythondocker:${{ steps.vars.outputs.tag }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/pythondocker:latest
    - name: Build (debian)
      uses: docker/build-push-action@v2
      with:
        context: ./docker/images/pythondocker-debian
        build-args: |
          N_VERSION=${{ steps.vars.outputs.tag }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/pythondocker:${{ steps.vars.outputs.tag }}-debian
          ${{ secrets.DOCKER_HUB_USERNAME }}/pythondocker:latest-debian
